spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        ejb:
          naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/G4
    username: grupo4
    password: helloworld
    driver-class-name: org.gjt.mm.mysql.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG